/*Data Aggregation and Transformation */


/* •	Total Revenue per Category:
Use SUM() to calculate the total revenue generated by each product category.
Include the number of orders per category as well.
*/

select p.category ,ROUND(SUM(o.price), 2) as total_revenue , count(o.order_id) as number_of_order
from order_items o inner join products p
ON o.product_id = p.product_id group by p.category;

/* 
Monthly Sales Analysis:
Create a report showing total sales for each month.
Use the DATE_FORMAT() function to group sales by month and year.
*/
SELECT  
  DATE_FORMAT(order_date, '%Y-%m') AS month_year,
  ROUND(SUM(total_amount), 2) AS total_sales
FROM 
  orders
GROUP BY 
  month_year
ORDER BY 
  month_year;
 
 
 /*•	Customer Lifetime Value (CLV):
o	Calculate the total revenue generated by each customer, considering their total orders and order frequency.
o	Use GROUP BY and aggregate functions like SUM() and COUNT().
*/

SELECT 
  customer_id, 
  DATE_FORMAT(order_date, "%Y") AS year,
  ROUND(SUM(total_amount), 2) AS total_revenue,
  COUNT(order_id) AS order_count
FROM 
  orders
GROUP BY 
  customer_id, DATE_FORMAT(order_date, "%Y")
ORDER BY 
  customer_id, year;
